apiVersion: apps/v1
kind: Deployment
metadata:
  name: newboots-server
  labels:
    app: newboots-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newboots-server
  template:
    metadata:
      labels:
        app: newboots-server
    spec:
      containers:
        - name: newboots-server
          image: ghcr.io/kenahrens/newboots-server:latest
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 3
            timeoutSeconds: 1
            httpGet:
              path: /actuator/health
              port: http
          resources:
            requests:
              cpu: "0.1"
              memory: 512Mi
            limits:
              cpu: "0.5"
              memory: 1024Mi
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: grpc
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: APP_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MONGODB_URI
              value: "mongodb://mongo:27017/newboots?tls=true&tlsInsecure=true"
            - name: MYSQL_URL
              value: "jdbc:mysql://mysql:3306/newboots?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
            - name: MYSQL_USERNAME
              value: "newboots"
            - name: MYSQL_PASSWORD
              value: "newboots"
          envFrom:
            - configMapRef:
                name: newboots-server
