apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mongo-tls
  files:
    - cert.pem
    - ca.pem
resources:
  - namespace.yaml
  - deploy.yaml
  - svc.yaml
  - cm.yaml
  - client-deploy.yaml
  - mongo-deploy.yaml
  - mongo-svc.yaml
  - mysql-deploy.yaml
  - mysql-svc.yaml
